name: User Guided Blog
favicon: null
layout_spectrum: 0.49864
typography_spectrum: 0.89608
title: User Guided Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#437171'
    - '#000000'
    - '#9db5b5'
    - '#333333'
  brandStrength: 0.05580706032924354
  lightness: 0.30873759486712515
  saturation: 0.4367158336099237
  rhythmicContrast: 0.9039094524923712
purpose: []
